routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubcategoryController;
use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/view-products/{id}', [App\Http\Controllers\HomeController::class, 'view_products']);
Route::get('/product-details/{id}', [App\Http\Controllers\HomeController::class, 'single_product_details']);




//Backend Route
Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/dashboard', [App\Http\Controllers\AdminController::class, 'index']);

    Route::resource('categories', CategoryController::class);
    Route::resource('subcategories', SubcategoryController::class);
    Route::resource('products', ProductController::class);


});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'subcategory_id',
        'name',
        'slug',
        'small_description',
        'description',
        'original_price',
        'selling_price',
        'image',
        'tax',
        'qty',
    ];

    public function subcategory() {
        return $this->belongsTo(Subcategory::class, 'subcategory_id', 'id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Subcategory;
use App\Models\Category;
use Illuminate\Support\Facades\File;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::with('subcategory')->get();
        $subcategories = Subcategory::all();
        return view('admin.products.index', compact('products', 'subcategories'));
    }

    public function show($id)
    {
        // $products = Product::with('subcategory')->get();
        $products = Product::where('id', $id)->first();
        $subcategories = Subcategory::all();
        return view('admin.products.show', compact('products', 'subcategories'));
    }

    public function create()
    {
        $subcategories = Subcategory::all();
        return view('admin.products.create', compact('subcategories'));
    }

    public function store(Request $request)
    {
        $product = new Product();
        if($request->hasFile('image'))
        {
            $file = $request->file('image');
            $ext = $file->getClientOriginalExtension();
            $filename = time().'.'.$ext;
            $file->move('assets/uploads/product/',$filename);
            $product->image = $filename;
        }
        $product->name = $request->input('name');
        $product->slug = $request->input('slug');
        $product->small_description = $request->input('small_description');
        $product->description = $request->input('description');
        $product->original_price = $request->input('original_price');
        $product->selling_price = $request->input('selling_price');
        $product->tax = $request->input('tax');
        $product->qty = $request->input('qty');
        $product->subcategory_id = $request->input('subcategory_id');
        $product->save();

        return redirect()->route('products.index')->with('status', "Product Added Successfully");
    }

    public function edit(Product $product)
    {
        $subcategories = Subcategory::all();
        return view('admin.products.edit', compact('product', 'subcategories'));
    }

    public function update(Request $request, Product $product)
    {
        if($request->hasFile('image'))
        {
            $path = 'assets/uploads/products/'.$product->image;
            if(File::exists($path))
            {
                File::delete($path);
            }
            $file = $request->file('image');
            $ext = $file->getClientOriginalExtension();
            $filename = time().'.'.$ext;
            $file->move('assets/uploads/product/',$filename);
            $product->image = $filename;
        }
        $product->name = $request->input('name');
        $product->slug = $request->input('slug');
        $product->small_description = $request->input('small_description');
        $product->description = $request->input('description');
        $product->original_price = $request->input('original_price');
        $product->selling_price = $request->input('selling_price');
        $product->tax = $request->input('tax');
        $product->qty = $request->input('qty');
        $product->subcategory_id = $request->input('subcategory_id');
        $product->save();

        return redirect()->route('products.index')->with('status', "Product Updated Successfully");
    }

    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')->with('status', "Product Deleted Successfully");
    }



}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container d-flex">
        <a class="m-4" href="{{ route('categories.index') }}">All Categories</a>
        <a class="m-4" href="{{ route('subcategories.index') }}">All Sub Categories</a>
        <a class="m-4" href="{{ route('products.index') }}">All Products</a>
    </div>
    <div class="container card">

        <h2 class="mx-3 mt-3">Add Product</h2>
        <hr>

        <div class="card-body">
            <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">

                    <div class="col-md-12 mb-3">
                        <select class="form-select" name="subcategory_id">
                            <option value="">Select a Sub Category *</option>
                            @foreach ($subcategories as $item )
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Name:</label>
                        <input type="text" class="form-control" name="name">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Slug:</label>
                        <input type="text" class="form-control" name="slug">
                    </div>

                    <div class="col-md-12 mb-3">
                        <label class="form-label fw-bold" for="">Small Description:</label>
                        <textarea name="small_description" rows="2" class="form-control"></textarea>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label class="form-label fw-bold" for="">Description:</label>
                        <textarea name="description" rows="2" class="form-control"></textarea>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Original Price:</label>
                        <input type="number" name="original_price" class="form-control">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Selling Price:</label>
                        <input type="number" name="selling_price" class="form-control">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Tax:</label>
                        <input type="number" name="tax" class="form-control">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Quantity:</label>
                        <input type="number" name="qty" class="form-control">
                    </div>

                    <div class="col-md-12">
                        <input type="file" class="form-control" name="image">
                    </div>
                    <div class="col-md-12 mt-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container d-flex">
        <a class="m-4" href="{{ route('categories.index') }}">All Categories</a>
        <a class="m-4" href="{{ route('subcategories.index') }}">All Sub Categories</a>
        <a class="m-4" href="{{ route('products.index') }}">All Products</a>
    </div>
    <div class="container card">

        <h2 class="mx-3 mt-3">Edit Product</h2>
        <hr>

        <div class="card-body">
            <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-12 mb-3">
                    <label class="form-label fw-bold" for="">Sub Category Name:</label>
                    <select name="subcategory_id" id="subcategory_id" class="form-select">
                        @foreach ($subcategories as $subcategory)
                            <option value="{{ $subcategory->id }}" {{ $subcategory->id === $product->subcategory_id ? 'selected' : '' }}>
                                {{ $subcategory->name }}
                            </option>
                        @endforeach
                    </select>
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Name:</label>
                        <input type="text" class="form-control" name="name" value="{{ $product->name }}">
                    </div>

                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Slug:</label>
                        <input type="text" class="form-control" name="slug" value="{{ $product->slug }}">
                    </div>

                    <div class="col-md-12 mb-3">
                        <label class="form-label fw-bold" for="">Small Description:</label>
                        <textarea name="small_description" rows="2" class="form-control"> {{ $product->small_description }}</textarea>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label class="form-label fw-bold" for="">Description:</label>
                        <textarea name="description" rows="2" class="form-control">{{ $product->description }}</textarea>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Original Price:</label>
                        <input type="number" name="original_price" class="form-control" value="{{ $product->original_price }}">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Selling Price:</label>
                        <input type="number" name="selling_price" class="form-control" value="{{ $product->selling_price }}">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Tax:</label>
                        <input type="number" name="tax" class="form-control" value="{{ $product->tax }}">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="form-label fw-bold" for="">Quantity:</label>
                        <input type="number" name="qty" class="form-control" value="{{ $product->qty }}">
                    </div>
                    @if ($product->image)
                        <img src="{{ asset('assets/uploads/product/'.$product->image) }}" alt="" style="width:200px; height:200px">
                    @endif
                    <div class="col-md-12">
                        <input type="file" class="form-control" name="image">
                    </div>
                    <div class="col-md-12 mt-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container d-flex">
        <a class="m-4" href="{{ route('categories.index') }}">All Categories</a>
        <a class="m-4" href="{{ route('subcategories.index') }}">All Sub Categories</a>
        <a class="m-4" href="{{ route('products.index') }}">All Products</a>
    </div>
    <div class="container">
        <div class="card shadow product_data mb-5">
            <div class="card-body">
                @if (Session::has('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('status') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <div class="row">
                    <div class="class mx-auto">
                        <h2>
                            Product List
                            <a href="{{ route('products.create') }}" class="btn btn-sm btn-primary float-end">Add New Product</a>
                        </h2>
                        <hr>
                    </div>
                    <div class="mx-auto">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Sub Category</th>
                                    <th>Name</th>
                                    <th>Selling Price</th>
                                    <th>Image</th>
                                    <th>Actions</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($products as $product)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $product->subcategory->name }}</td>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->selling_price }}</td>
                                        <td>
                                            <img src="{{ asset('assets/uploads/product/'.$product->image) }}" alt="Image Loading" style="width:80px; height:80px">
                                        </td>
                                        <td colspan="2" >
                                            <a class="btn btn-sm btn-success" href="{{ route('products.show', $product->id) }}">Details</a>
                                            <a class="btn btn-sm btn-info" href="{{ route('products.edit', $product->id) }}">Edit</a>

                                            <form class="d-inline" action="{{ route('products.destroy', $product->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/products/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container d-flex">
        <a class="m-4" href="{{ route('categories.index') }}">All Categories</a>
        <a class="m-4" href="{{ route('subcategories.index') }}">All Sub Categories</a>
        <a class="m-4" href="{{ route('products.index') }}">All Products</a>
    </div>

    <div class="container">
        <div class="card shadow product_data mb-5">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4 border-right">
                        <img style="height: 300px" src="{{ asset('assets/uploads/product/'.$products->image) }}" class="w-100" alt="">
                    </div>
                    <div class="col-md-8">
                        <h2 class="mb-0">
                            {{ $products->name }}
                        </h2>
                        <hr>
                        <label class="me-3" for="">Original Price : <s style="color: red">TK {{ $products->original_price }}</s></label>
                        <label class="fw-bold" for="">Selling Price : TK {{ $products->selling_price }}</label>
                        <p class="mt-3">
                            {{ $products->small_description }}
                        </p>
                        <hr>
                        <div class="row mt-2">
                            <div class="col-md-2">
                                <input type="hidden" value="{{ $products->id }}" class="product_id mb-2">
                                <label for="Quantity">Quantity</label>
                                <div class="input-group text-center mt-2" style="width: 105px;">
                                    <button class="input-group-text decrement-btn">-</button>
                                    <input type="text" name="Quantity" value="{{ $products->qty }}" class="form-control qty-input">
                                    <button class="input-group-text increment-btn">+</button>
                                </div>
                            </div>
                            <div class="col-md-10 mt-2">
                                <br/>

                                <button type="submit" class="btn btn-primary me-3 float-start">Add to Cart  <i class="fa fa-shopping-cart"></i></button>
                                <button type="button" class="btn btn-success me-3 float-start">Add to Wishlist  <i class="fa fa-heart"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <h3 class="p-3">Product Description</h3>
                <p class="ps-3">
                    {{  $products->description  }}
                </p>
            </div>
        </div>
    </div>
@endsection